[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

# Set upload baud rate
upload_speed = 921600
monitor_speed = 115200

# Need larger than default code size
board_build.partitions = min_spiffs.csv

# Library Dependencies
lib_deps =
    fastled/FastLED@3.6.0
    https://github.com/jovankoledin/ESP32-ANCS-Notifications.git #0.0.1
    https://github.com/arduino-libraries/Arduino_ESP32_OTA #0.3.1
    https://github.com/arduino-libraries/ArduinoHttpClient #0.6.1

# Options for OTA Upload
#upload_protocol = espota
#upload_port = LightPhone-ESP32.local # 192.168.0.110